import Head from 'next/head'
import Image from 'next/image'
import a from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={[a.container, a.test123].join(" ")}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={a.main}>
        </main>
    </div>
  )
}
