import Head from "next/head";
import Image from "next/image";
import a from "../styles/Home.module.css";
import HeroCarousel from "../common/carousel";
import Content from "../common/content";
import { Row } from "react-bootstrap";
import CardDemo from "../common/card";
import TabDemo from "../common/tab";

export default function Home() {
  return (
    <div className={[a.container, a.test123].join(" ")}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={a.main}>
        <HeroCarousel />
        <Content />
        <Row>
        <CardDemo/>
        <CardDemo/>
        <CardDemo/>
        </Row>
        <Row>
        <TabDemo />
        </Row>
      </main>
    </div>
  );
}
